"""Model metadata from the official command-code@1.79.2 bundled catalogue."""
MODELS = {'MiniMaxAI/MiniMax-M2.5': {'billing_mode': 'paid',
                            'catalog_source': 'command-code@1.79.2',
                            'context_length': 200000,
                            'entitlement': 'subscription',
                            'id': 'MiniMaxAI/MiniMax-M2.5',
                            'min_plan': 'go',
                            'name': 'MiniMax M2.5',
                            'native_protocol': 'chat',
                            'reference_pricing': {'input': 0.3, 'output': 1.2, 'unit': 'USD/1M tokens'}},
 'MiniMaxAI/MiniMax-M2.7': {'billing_mode': 'paid',
                            'catalog_source': 'command-code@1.79.2',
                            'entitlement': 'subscription',
                            'id': 'MiniMaxAI/MiniMax-M2.7',
                            'min_plan': 'go',
                            'name': 'MiniMax M2.7',
                            'native_protocol': 'chat',
                            'reference_pricing': {'input': 0.3, 'output': 1.2, 'unit': 'USD/1M tokens'}},
 'MiniMaxAI/MiniMax-M3': {'billing_mode': 'paid',
                          'catalog_source': 'command-code@1.79.2',
                          'context_length': 1000000,
                          'entitlement': 'subscription',
                          'id': 'MiniMaxAI/MiniMax-M3',
                          'min_plan': 'go',
                          'name': 'MiniMax M3',
                          'native_protocol': 'chat',
                          'reference_pricing': {'input': 0.3, 'output': 1.2, 'unit': 'USD/1M tokens'}},
 'Qwen/Qwen3.6-Max-Preview': {'billing_mode': 'paid',
                              'catalog_source': 'command-code@1.79.2',
                              'entitlement': 'subscription',
                              'id': 'Qwen/Qwen3.6-Max-Preview',
                              'min_plan': 'go',
                              'name': 'Qwen 3.6 Max Preview',
                              'native_protocol': 'chat',
                              'reference_pricing': {'input': 1.3, 'output': 7.8, 'unit': 'USD/1M tokens'}},
 'Qwen/Qwen3.6-Plus': {'billing_mode': 'paid',
                       'catalog_source': 'command-code@1.79.2',
                       'entitlement': 'subscription',
                       'id': 'Qwen/Qwen3.6-Plus',
                       'min_plan': 'go',
                       'name': 'Qwen 3.6 Plus',
                       'native_protocol': 'chat',
                       'reference_pricing': {'input': 0.5, 'output': 3.0, 'unit': 'USD/1M tokens'}},
 'Qwen/Qwen3.7-Flash': {'billing_mode': 'paid',
                        'catalog_source': 'command-code@1.79.2',
                        'context_length': 1000000,
                        'entitlement': 'subscription',
                        'id': 'Qwen/Qwen3.7-Flash',
                        'min_plan': 'go',
                        'name': 'Qwen 3.7 Flash',
                        'native_protocol': 'chat',
                        'reference_pricing': {'input': 0.03, 'output': 0.13, 'unit': 'USD/1M tokens'}},
 'Qwen/Qwen3.7-Max': {'billing_mode': 'paid',
                      'catalog_source': 'command-code@1.79.2',
                      'context_length': 1000000,
                      'entitlement': 'subscription',
                      'id': 'Qwen/Qwen3.7-Max',
                      'min_plan': 'go',
                      'name': 'Qwen 3.7 Max',
                      'native_protocol': 'chat',
                      'reference_pricing': {'input': 2.5, 'output': 7.5, 'unit': 'USD/1M tokens'}},
 'Qwen/Qwen3.7-Plus': {'billing_mode': 'paid',
                       'catalog_source': 'command-code@1.79.2',
                       'context_length': 1000000,
                       'entitlement': 'subscription',
                       'id': 'Qwen/Qwen3.7-Plus',
                       'min_plan': 'go',
                       'name': 'Qwen 3.7 Plus',
                       'native_protocol': 'chat',
                       'reference_pricing': {'input': 0.4, 'output': 1.6, 'unit': 'USD/1M tokens'}},
 'Qwen/Qwen3.8-27B': {'billing_mode': 'paid',
                      'catalog_source': 'command-code@1.79.2',
                      'context_length': 262000,
                      'entitlement': 'subscription',
                      'id': 'Qwen/Qwen3.8-27B',
                      'min_plan': 'go',
                      'name': 'Qwen 3.8 27B',
                      'native_protocol': 'chat',
                      'reference_pricing': {'input': 0.4, 'output': 3.0, 'unit': 'USD/1M tokens'}},
 'Qwen/Qwen3.8-Flash': {'billing_mode': 'paid',
                        'catalog_source': 'command-code@1.79.2',
                        'context_length': 1000000,
                        'entitlement': 'subscription',
                        'id': 'Qwen/Qwen3.8-Flash',
                        'min_plan': 'go',
                        'name': 'Qwen 3.8 Flash',
                        'native_protocol': 'chat',
                        'reference_pricing': {'input': 0.16, 'output': 0.47, 'unit': 'USD/1M tokens'}},
 'Qwen/Qwen3.8-Max': {'billing_mode': 'paid',
                      'catalog_source': 'command-code@1.79.2',
                      'context_length': 1000000,
                      'entitlement': 'subscription',
                      'id': 'Qwen/Qwen3.8-Max',
                      'min_plan': 'go',
                      'name': 'Qwen 3.8 Max',
                      'native_protocol': 'chat',
                      'reference_pricing': {'input': 2.0, 'output': 6.0, 'unit': 'USD/1M tokens'}},
 'Qwen/Qwen3.8-Max-0902': {'billing_mode': 'paid',
                           'catalog_source': 'command-code@1.79.2',
                           'context_length': 1000000,
                           'entitlement': 'subscription',
                           'id': 'Qwen/Qwen3.8-Max-0902',
                           'min_plan': 'go',
                           'name': 'Qwen 3.8 Max 0902',
                           'native_protocol': 'chat',
                           'reference_pricing': {'input': 2.0, 'output': 6.0, 'unit': 'USD/1M tokens'}},
 'Qwen/Qwen3.8-Omni-Flash': {'billing_mode': 'paid',
                             'catalog_source': 'command-code@1.79.2',
                             'context_length': 1000000,
                             'entitlement': 'subscription',
                             'id': 'Qwen/Qwen3.8-Omni-Flash',
                             'min_plan': 'go',
                             'name': 'Qwen 3.8 Omni Flash',
                             'native_protocol': 'chat',
                             'reference_pricing': {'input': 0.15, 'output': 0.47, 'unit': 'USD/1M tokens'}},
 'claude-fable-5': {'billing_mode': 'paid',
                    'catalog_source': 'command-code@1.79.2',
                    'context_length': 1000000,
                    'entitlement': 'subscription',
                    'id': 'claude-fable-5',
                    'min_plan': 'max',
                    'name': 'Claude Fable 5',
                    'native_protocol': 'chat',
                    'reference_pricing': {'input': 10.0, 'output': 50.0, 'unit': 'USD/1M tokens'}},
 'claude-fable-5-1': {'billing_mode': 'paid',
                      'catalog_source': 'command-code@1.79.2',
                      'context_length': 1000000,
                      'entitlement': 'subscription',
                      'id': 'claude-fable-5-1',
                      'min_plan': 'max',
                      'name': 'Claude Fable 5.1',
                      'native_protocol': 'chat',
                      'reference_pricing': {'input': 10.0, 'output': 50.0, 'unit': 'USD/1M tokens'}},
 'claude-haiku-4-5-20251001': {'billing_mode': 'paid',
                               'catalog_source': 'command-code@1.79.2',
                               'context_length': 200000,
                               'entitlement': 'subscription',
                               'id': 'claude-haiku-4-5-20251001',
                               'min_plan': 'pro',
                               'name': 'Claude Haiku 4.5',
                               'native_protocol': 'chat',
                               'reference_pricing': {'input': 1.0, 'output': 5.0, 'unit': 'USD/1M tokens'}},
 'claude-haiku-5-5': {'billing_mode': 'paid',
                      'catalog_source': 'command-code@1.79.2',
                      'context_length': 1000000,
                      'entitlement': 'subscription',
                      'id': 'claude-haiku-5-5',
                      'min_plan': 'goat',
                      'name': 'Claude Haiku 5.5',
                      'native_protocol': 'chat',
                      'reference_pricing': {'input': 0.1, 'output': 0.5, 'unit': 'USD/1M tokens'}},
 'claude-opus-4-7': {'billing_mode': 'paid',
                     'catalog_source': 'command-code@1.79.2',
                     'context_length': 1000000,
                     'entitlement': 'subscription',
                     'id': 'claude-opus-4-7',
                     'min_plan': 'max',
                     'name': 'Claude Opus 4.7',
                     'native_protocol': 'chat',
                     'reference_pricing': {'input': 5.0, 'output': 25.0, 'unit': 'USD/1M tokens'}},
 'claude-opus-4-8': {'billing_mode': 'paid',
                     'catalog_source': 'command-code@1.79.2',
                     'context_length': 1000000,
                     'entitlement': 'subscription',
                     'id': 'claude-opus-4-8',
                     'min_plan': 'max',
                     'name': 'Claude Opus 4.8',
                     'native_protocol': 'chat',
                     'reference_pricing': {'input': 5.0, 'output': 25.0, 'unit': 'USD/1M tokens'}},
 'claude-opus-5': {'billing_mode': 'paid',
                   'catalog_source': 'command-code@1.79.2',
                   'context_length': 1000000,
                   'entitlement': 'subscription',
                   'id': 'claude-opus-5',
                   'min_plan': 'max',
                   'name': 'Claude Opus 5',
                   'native_protocol': 'chat',
                   'reference_pricing': {'input': 5.0, 'output': 25.0, 'unit': 'USD/1M tokens'}},
 'claude-opus-5-5': {'billing_mode': 'paid',
                     'catalog_source': 'command-code@1.79.2',
                     'context_length': 1000000,
                     'entitlement': 'subscription',
                     'id': 'claude-opus-5-5',
                     'min_plan': 'max',
                     'name': 'Claude Opus 5.5',
                     'native_protocol': 'chat',
                     'reference_pricing': {'input': 4.0, 'output': 20.0, 'unit': 'USD/1M tokens'}},
 'claude-sonnet-4-6': {'billing_mode': 'paid',
                       'catalog_source': 'command-code@1.79.2',
                       'context_length': 1000000,
                       'entitlement': 'subscription',
                       'id': 'claude-sonnet-4-6',
                       'min_plan': 'pro',
                       'name': 'Claude Sonnet 4.6',
                       'native_protocol': 'chat',
                       'reference_pricing': {'input': 3.0, 'output': 15.0, 'unit': 'USD/1M tokens'}},
 'claude-sonnet-5': {'billing_mode': 'paid',
                     'catalog_source': 'command-code@1.79.2',
                     'context_length': 1000000,
                     'entitlement': 'subscription',
                     'id': 'claude-sonnet-5',
                     'min_plan': 'pro',
                     'name': 'Claude Sonnet 5',
                     'native_protocol': 'chat',
                     'reference_pricing': {'input': 2.0, 'output': 10.0, 'unit': 'USD/1M tokens'}},
 'claude-sonnet-5-5': {'billing_mode': 'paid',
                       'catalog_source': 'command-code@1.79.2',
                       'context_length': 1000000,
                       'entitlement': 'subscription',
                       'id': 'claude-sonnet-5-5',
                       'min_plan': 'goat',
                       'name': 'Claude Sonnet 5.5',
                       'native_protocol': 'chat',
                       'reference_pricing': {'input': 2.0, 'output': 10.0, 'unit': 'USD/1M tokens'}},
 'deepseek/deepseek-v4-flash': {'billing_mode': 'paid',
                                'catalog_source': 'command-code@1.79.2',
                                'context_length': 1000000,
                                'entitlement': 'subscription',
                                'id': 'deepseek/deepseek-v4-flash',
                                'min_plan': 'go',
                                'name': 'DeepSeek V4 Flash (latest)',
                                'native_protocol': 'chat',
                                'reference_pricing': {'input': 0.15, 'output': 0.6, 'unit': 'USD/1M tokens'}},
 'deepseek/deepseek-v4-flash-fast': {'billing_mode': 'paid',
                                     'catalog_source': 'command-code@1.79.2',
                                     'context_length': 1000000,
                                     'entitlement': 'subscription',
                                     'id': 'deepseek/deepseek-v4-flash-fast',
                                     'min_plan': 'go',
                                     'name': 'DeepSeek V4 Flash Fast',
                                     'native_protocol': 'chat',
                                     'reference_pricing': {'input': 0.28,
                                                           'output': 0.56,
                                                           'unit': 'USD/1M tokens'}},
 'deepseek/deepseek-v4-flash-vision-exp': {'billing_mode': 'paid',
                                           'catalog_source': 'command-code@1.79.2',
                                           'context_length': 1000000,
                                           'entitlement': 'subscription',
                                           'id': 'deepseek/deepseek-v4-flash-vision-exp',
                                           'min_plan': 'go',
                                           'name': 'DeepSeek V4 Flash Vision (exp)',
                                           'native_protocol': 'chat',
                                           'reference_pricing': {'input': 0.15,
                                                                 'output': 0.6,
                                                                 'unit': 'USD/1M tokens'}},
 'deepseek/deepseek-v4-pro': {'billing_mode': 'paid',
                              'catalog_source': 'command-code@1.79.2',
                              'context_length': 1000000,
                              'entitlement': 'subscription',
                              'id': 'deepseek/deepseek-v4-pro',
                              'min_plan': 'go',
                              'name': 'DeepSeek V4 Pro (latest)',
                              'native_protocol': 'chat',
                              'reference_pricing': {'input': 0.66, 'output': 1.98, 'unit': 'USD/1M tokens'}},
 'deepseek/deepseek-v4.1-flash': {'billing_mode': 'paid',
                                  'catalog_source': 'command-code@1.79.2',
                                  'context_length': 1000000,
                                  'entitlement': 'subscription',
                                  'id': 'deepseek/deepseek-v4.1-flash',
                                  'min_plan': 'go',
                                  'name': 'DeepSeek V4.1 Flash',
                                  'native_protocol': 'chat',
                                  'reference_pricing': {'input': 0.15,
                                                        'output': 0.6,
                                                        'unit': 'USD/1M tokens'}},
 'deepseek/deepseek-v4.1-flash-fast': {'billing_mode': 'paid',
                                       'catalog_source': 'command-code@1.79.2',
                                       'context_length': 1000000,
                                       'entitlement': 'subscription',
                                       'id': 'deepseek/deepseek-v4.1-flash-fast',
                                       'min_plan': 'go',
                                       'name': 'DeepSeek V4.1 Flash Fast',
                                       'native_protocol': 'chat',
                                       'reference_pricing': {'input': 0.16,
                                                             'output': 0.58,
                                                             'unit': 'USD/1M tokens'}},
 'google/gemini-3.1-flash-lite': {'billing_mode': 'paid',
                                  'catalog_source': 'command-code@1.79.2',
                                  'context_length': 1000000,
                                  'entitlement': 'subscription',
                                  'id': 'google/gemini-3.1-flash-lite',
                                  'min_plan': 'pro',
                                  'name': 'Gemini 3.1 Flash Lite',
                                  'native_protocol': 'chat',
                                  'reference_pricing': {'input': 0.25,
                                                        'output': 1.5,
                                                        'unit': 'USD/1M tokens'}},
 'google/gemini-3.5-flash': {'billing_mode': 'paid',
                             'catalog_source': 'command-code@1.79.2',
                             'context_length': 1000000,
                             'entitlement': 'subscription',
                             'id': 'google/gemini-3.5-flash',
                             'min_plan': 'pro',
                             'name': 'Gemini 3.5 Flash',
                             'native_protocol': 'chat',
                             'reference_pricing': {'input': 1.5, 'output': 9.0, 'unit': 'USD/1M tokens'}},
 'google/gemini-3.5-flash-lite': {'billing_mode': 'paid',
                                  'catalog_source': 'command-code@1.79.2',
                                  'context_length': 1000000,
                                  'entitlement': 'subscription',
                                  'id': 'google/gemini-3.5-flash-lite',
                                  'min_plan': 'pro',
                                  'name': 'Gemini 3.5 Flash Lite',
                                  'native_protocol': 'chat',
                                  'reference_pricing': {'input': 0.3,
                                                        'output': 2.5,
                                                        'unit': 'USD/1M tokens'}},
 'google/gemini-3.6-flash': {'billing_mode': 'paid',
                             'catalog_source': 'command-code@1.79.2',
                             'context_length': 1000000,
                             'entitlement': 'subscription',
                             'id': 'google/gemini-3.6-flash',
                             'min_plan': 'pro',
                             'name': 'Gemini 3.6 Flash',
                             'native_protocol': 'chat',
                             'reference_pricing': {'input': 1.5, 'output': 7.5, 'unit': 'USD/1M tokens'}},
 'google/gemini-3.7-flash': {'billing_mode': 'paid',
                             'catalog_source': 'command-code@1.79.2',
                             'context_length': 1050000,
                             'entitlement': 'subscription',
                             'id': 'google/gemini-3.7-flash',
                             'min_plan': 'goat',
                             'name': 'Gemini 3.7 Flash',
                             'native_protocol': 'chat',
                             'reference_pricing': {'input': 1.5, 'output': 7.5, 'unit': 'USD/1M tokens'}},
 'google/gemini-3.8-flash': {'billing_mode': 'paid',
                             'catalog_source': 'command-code@1.79.2',
                             'context_length': 1000000,
                             'entitlement': 'subscription',
                             'id': 'google/gemini-3.8-flash',
                             'min_plan': 'goat',
                             'name': 'Gemini 3.8 Flash',
                             'native_protocol': 'chat',
                             'reference_pricing': {'input': 1.5, 'output': 7.5, 'unit': 'USD/1M tokens'}},
 'gpt-5.3-codex': {'billing_mode': 'paid',
                   'catalog_source': 'command-code@1.79.2',
                   'context_length': 400000,
                   'entitlement': 'subscription',
                   'id': 'gpt-5.3-codex',
                   'min_plan': 'pro',
                   'name': 'GPT-5.3 Codex',
                   'native_protocol': 'chat',
                   'reference_pricing': {'input': 2.0, 'output': 8.0, 'unit': 'USD/1M tokens'}},
 'gpt-5.4': {'billing_mode': 'paid',
             'catalog_source': 'command-code@1.79.2',
             'context_length': 400000,
             'entitlement': 'subscription',
             'id': 'gpt-5.4',
             'min_plan': 'pro',
             'name': 'GPT-5.4',
             'native_protocol': 'chat',
             'reference_pricing': {'input': 2.5, 'output': 15.0, 'unit': 'USD/1M tokens'}},
 'gpt-5.4-mini': {'billing_mode': 'paid',
                  'catalog_source': 'command-code@1.79.2',
                  'context_length': 400000,
                  'entitlement': 'subscription',
                  'id': 'gpt-5.4-mini',
                  'min_plan': 'pro',
                  'name': 'GPT-5.4 Mini',
                  'native_protocol': 'chat',
                  'reference_pricing': {'input': 0.75, 'output': 4.5, 'unit': 'USD/1M tokens'}},
 'gpt-5.5': {'billing_mode': 'paid',
             'catalog_source': 'command-code@1.79.2',
             'context_length': 400000,
             'entitlement': 'subscription',
             'id': 'gpt-5.5',
             'min_plan': 'pro',
             'name': 'GPT-5.5',
             'native_protocol': 'chat',
             'reference_pricing': {'input': 5.0, 'output': 30.0, 'unit': 'USD/1M tokens'}},
 'gpt-5.6-luna': {'billing_mode': 'paid',
                  'catalog_source': 'command-code@1.79.2',
                  'context_length': 1050000,
                  'entitlement': 'subscription',
                  'id': 'gpt-5.6-luna',
                  'min_plan': 'go',
                  'name': 'GPT-5.6 Luna',
                  'native_protocol': 'chat',
                  'reference_pricing': {'input': 0.2, 'output': 1.2, 'unit': 'USD/1M tokens'}},
 'gpt-5.6-sol': {'billing_mode': 'paid',
                 'catalog_source': 'command-code@1.79.2',
                 'context_length': 1050000,
                 'entitlement': 'subscription',
                 'id': 'gpt-5.6-sol',
                 'min_plan': 'goat',
                 'name': 'GPT-5.6 Sol',
                 'native_protocol': 'chat',
                 'reference_pricing': {'input': 5.0, 'output': 30.0, 'unit': 'USD/1M tokens'}},
 'gpt-5.6-terra': {'billing_mode': 'paid',
                   'catalog_source': 'command-code@1.79.2',
                   'context_length': 1050000,
                   'entitlement': 'subscription',
                   'id': 'gpt-5.6-terra',
                   'min_plan': 'pro',
                   'name': 'GPT-5.6 Terra',
                   'native_protocol': 'chat',
                   'reference_pricing': {'input': 2.0, 'output': 12.0, 'unit': 'USD/1M tokens'}},
 'gpt-6-astra': {'billing_mode': 'paid',
                 'catalog_source': 'command-code@1.79.2',
                 'context_length': 1050000,
                 'entitlement': 'subscription',
                 'id': 'gpt-6-astra',
                 'min_plan': 'max',
                 'name': 'GPT-6 Astra',
                 'native_protocol': 'chat',
                 'reference_pricing': {'input': 10.0, 'output': 50.0, 'unit': 'USD/1M tokens'}},
 'gpt-6-luna': {'billing_mode': 'paid',
                'catalog_source': 'command-code@1.79.2',
                'context_length': 1050000,
                'entitlement': 'subscription',
                'id': 'gpt-6-luna',
                'min_plan': 'go',
                'name': 'GPT-6 Luna',
                'native_protocol': 'chat',
                'reference_pricing': {'input': 0.1, 'output': 0.5, 'unit': 'USD/1M tokens'}},
 'gpt-6-sol': {'billing_mode': 'paid',
               'catalog_source': 'command-code@1.79.2',
               'context_length': 1050000,
               'entitlement': 'subscription',
               'id': 'gpt-6-sol',
               'min_plan': 'pro',
               'name': 'GPT-6 Sol',
               'native_protocol': 'chat',
               'reference_pricing': {'input': 2.0, 'output': 10.0, 'unit': 'USD/1M tokens'}},
 'gpt-6.1-sol': {'billing_mode': 'paid',
                 'catalog_source': 'command-code@1.79.2',
                 'context_length': 1050000,
                 'entitlement': 'subscription',
                 'id': 'gpt-6.1-sol',
                 'min_plan': 'max',
                 'name': 'GPT-6.1 Sol',
                 'native_protocol': 'chat',
                 'reference_pricing': {'input': 2.0, 'output': 10.0, 'unit': 'USD/1M tokens'}},
 'inclusionai/ling-3.0-flash-sante:free': {'billing_mode': 'paid',
                                           'catalog_source': 'command-code@1.79.2',
                                           'context_length': 262000,
                                           'entitlement': 'subscription',
                                           'id': 'inclusionai/ling-3.0-flash-sante:free',
                                           'min_plan': 'go',
                                           'name': 'Ling 3.0 Flash Sante',
                                           'native_protocol': 'chat',
                                           'reference_pricing': {'input': 0.0,
                                                                 'output': 0.0,
                                                                 'unit': 'USD/1M tokens'}},
 'inclusionai/ling-3.1-flash:free': {'billing_mode': 'paid',
                                     'catalog_source': 'command-code@1.79.2',
                                     'context_length': 262000,
                                     'entitlement': 'subscription',
                                     'id': 'inclusionai/ling-3.1-flash:free',
                                     'min_plan': 'go',
                                     'name': 'Ling 3.1 Flash',
                                     'native_protocol': 'chat',
                                     'reference_pricing': {'input': 0.0,
                                                           'output': 0.0,
                                                           'unit': 'USD/1M tokens'}},
 'meituan/LongCat-2.0': {'billing_mode': 'paid',
                         'catalog_source': 'command-code@1.79.2',
                         'context_length': 1050000,
                         'entitlement': 'subscription',
                         'id': 'meituan/LongCat-2.0',
                         'min_plan': 'go',
                         'name': 'LongCat 2.0',
                         'native_protocol': 'chat',
                         'reference_pricing': {'input': 0.3, 'output': 1.2, 'unit': 'USD/1M tokens'}},
 'meta/muse-spark-1.1': {'billing_mode': 'paid',
                         'catalog_source': 'command-code@1.79.2',
                         'context_length': 1050000,
                         'entitlement': 'subscription',
                         'id': 'meta/muse-spark-1.1',
                         'min_plan': 'pro',
                         'name': 'Muse Spark 1.1',
                         'native_protocol': 'chat',
                         'reference_pricing': {'input': 1.25, 'output': 4.25, 'unit': 'USD/1M tokens'}},
 'meta/muse-spark-1.2': {'billing_mode': 'paid',
                         'catalog_source': 'command-code@1.79.2',
                         'context_length': 1050000,
                         'entitlement': 'subscription',
                         'id': 'meta/muse-spark-1.2',
                         'min_plan': 'goat',
                         'name': 'Muse Spark 1.2',
                         'native_protocol': 'chat',
                         'reference_pricing': {'input': 1.25, 'output': 4.25, 'unit': 'USD/1M tokens'}},
 'meta/muse-spark-1.2-contributor': {'billing_mode': 'paid',
                                     'catalog_source': 'command-code@1.79.2',
                                     'context_length': 1050000,
                                     'entitlement': 'subscription',
                                     'id': 'meta/muse-spark-1.2-contributor',
                                     'min_plan': 'go',
                                     'name': 'Muse Spark 1.2 Contributor',
                                     'native_protocol': 'chat',
                                     'reference_pricing': {'input': 0.1,
                                                           'output': 0.2,
                                                           'unit': 'USD/1M tokens'}},
 'meta/muse-spark-1.3': {'billing_mode': 'paid',
                         'catalog_source': 'command-code@1.79.2',
                         'context_length': 1050000,
                         'entitlement': 'subscription',
                         'id': 'meta/muse-spark-1.3',
                         'min_plan': 'goat',
                         'name': 'Muse Spark 1.3',
                         'native_protocol': 'chat',
                         'reference_pricing': {'input': 1.25, 'output': 4.25, 'unit': 'USD/1M tokens'}},
 'meta/muse-spark-1.3-contributor': {'billing_mode': 'paid',
                                     'catalog_source': 'command-code@1.79.2',
                                     'context_length': 1050000,
                                     'entitlement': 'subscription',
                                     'id': 'meta/muse-spark-1.3-contributor',
                                     'min_plan': 'go',
                                     'name': 'Muse Spark 1.3 Contributor',
                                     'native_protocol': 'chat',
                                     'reference_pricing': {'input': 0.1,
                                                           'output': 0.2,
                                                           'unit': 'USD/1M tokens'}},
 'mistral/mistral-large-4': {'billing_mode': 'paid',
                             'catalog_source': 'command-code@1.79.2',
                             'context_length': 524000,
                             'entitlement': 'subscription',
                             'id': 'mistral/mistral-large-4',
                             'min_plan': 'go',
                             'name': 'Mistral Large 4',
                             'native_protocol': 'chat',
                             'reference_pricing': {'input': 1.36, 'output': 4.18, 'unit': 'USD/1M tokens'}},
 'moonshotai/Kimi-K2.5': {'billing_mode': 'paid',
                          'catalog_source': 'command-code@1.79.2',
                          'context_length': 256000,
                          'entitlement': 'subscription',
                          'id': 'moonshotai/Kimi-K2.5',
                          'min_plan': 'go',
                          'name': 'Kimi K2.5',
                          'native_protocol': 'chat',
                          'reference_pricing': {'input': 0.6, 'output': 3.0, 'unit': 'USD/1M tokens'}},
 'moonshotai/Kimi-K2.6': {'billing_mode': 'paid',
                          'catalog_source': 'command-code@1.79.2',
                          'context_length': 256000,
                          'entitlement': 'subscription',
                          'id': 'moonshotai/Kimi-K2.6',
                          'min_plan': 'go',
                          'name': 'Kimi K2.6',
                          'native_protocol': 'chat',
                          'reference_pricing': {'input': 0.95, 'output': 4.0, 'unit': 'USD/1M tokens'}},
 'moonshotai/Kimi-K2.7-Code': {'billing_mode': 'paid',
                               'catalog_source': 'command-code@1.79.2',
                               'context_length': 256000,
                               'entitlement': 'subscription',
                               'id': 'moonshotai/Kimi-K2.7-Code',
                               'min_plan': 'go',
                               'name': 'Kimi K2.7 Code',
                               'native_protocol': 'chat',
                               'reference_pricing': {'input': 0.95, 'output': 4.0, 'unit': 'USD/1M tokens'}},
 'moonshotai/Kimi-K2.7-Code-Highspeed': {'billing_mode': 'paid',
                                         'catalog_source': 'command-code@1.79.2',
                                         'context_length': 262000,
                                         'entitlement': 'subscription',
                                         'id': 'moonshotai/Kimi-K2.7-Code-Highspeed',
                                         'min_plan': 'go',
                                         'name': 'Kimi K2.7 Code HighSpeed',
                                         'native_protocol': 'chat',
                                         'reference_pricing': {'input': 1.9,
                                                               'output': 8.0,
                                                               'unit': 'USD/1M tokens'}},
 'moonshotai/Kimi-K3': {'billing_mode': 'paid',
                        'catalog_source': 'command-code@1.79.2',
                        'context_length': 1000000,
                        'entitlement': 'subscription',
                        'id': 'moonshotai/Kimi-K3',
                        'min_plan': 'go',
                        'name': 'Kimi K3',
                        'native_protocol': 'chat',
                        'reference_pricing': {'input': 3.0, 'output': 15.0, 'unit': 'USD/1M tokens'}},
 'nvidia/nemotron-3-ultra-550b-a55b': {'billing_mode': 'paid',
                                       'catalog_source': 'command-code@1.79.2',
                                       'context_length': 1000000,
                                       'entitlement': 'subscription',
                                       'id': 'nvidia/nemotron-3-ultra-550b-a55b',
                                       'min_plan': 'go',
                                       'name': 'Nemotron 3 Ultra',
                                       'native_protocol': 'chat',
                                       'reference_pricing': {'input': 0.6,
                                                             'output': 2.4,
                                                             'unit': 'USD/1M tokens'}},
 'poolside/laguna-s-2.1-free': {'billing_mode': 'paid',
                                'catalog_source': 'command-code@1.79.2',
                                'context_length': 256000,
                                'entitlement': 'subscription',
                                'id': 'poolside/laguna-s-2.1-free',
                                'min_plan': 'go',
                                'name': 'Laguna S 2.1',
                                'native_protocol': 'chat',
                                'reference_pricing': {'input': 0.0, 'output': 0.0, 'unit': 'USD/1M tokens'}},
 'sakana/fugu-ultra': {'billing_mode': 'paid',
                       'catalog_source': 'command-code@1.79.2',
                       'context_length': 1000000,
                       'entitlement': 'subscription',
                       'id': 'sakana/fugu-ultra',
                       'min_plan': 'max',
                       'name': 'Fugu Ultra',
                       'native_protocol': 'chat',
                       'reference_pricing': {'input': 5.0, 'output': 30.0, 'unit': 'USD/1M tokens'}},
 'stealth/glyph-cluster:free': {'billing_mode': 'paid',
                                'catalog_source': 'command-code@1.79.2',
                                'context_length': 256000,
                                'entitlement': 'subscription',
                                'id': 'stealth/glyph-cluster:free',
                                'min_plan': 'go',
                                'name': 'Glyph Cluster',
                                'native_protocol': 'chat',
                                'reference_pricing': {'input': 0.0, 'output': 0.0, 'unit': 'USD/1M tokens'}},
 'stepfun/Step-3.5-Flash': {'billing_mode': 'paid',
                            'catalog_source': 'command-code@1.79.2',
                            'context_length': 262000,
                            'entitlement': 'subscription',
                            'id': 'stepfun/Step-3.5-Flash',
                            'min_plan': 'go',
                            'name': 'Step 3.5 Flash',
                            'native_protocol': 'chat',
                            'reference_pricing': {'input': 0.09, 'output': 0.3, 'unit': 'USD/1M tokens'}},
 'stepfun/Step-3.7-Flash': {'billing_mode': 'paid',
                            'catalog_source': 'command-code@1.79.2',
                            'context_length': 256000,
                            'entitlement': 'subscription',
                            'id': 'stepfun/Step-3.7-Flash',
                            'min_plan': 'go',
                            'name': 'Step 3.7 Flash',
                            'native_protocol': 'chat',
                            'reference_pricing': {'input': 0.2, 'output': 1.15, 'unit': 'USD/1M tokens'}},
 'stepfun/Step-5-Preview': {'billing_mode': 'paid',
                            'catalog_source': 'command-code@1.79.2',
                            'context_length': 1000000,
                            'entitlement': 'subscription',
                            'id': 'stepfun/Step-5-Preview',
                            'min_plan': 'go',
                            'name': 'Step 5 Preview',
                            'native_protocol': 'chat',
                            'reference_pricing': {'input': 1.0, 'output': 2.7, 'unit': 'USD/1M tokens'}},
 'tencent/hy3-paid': {'billing_mode': 'paid',
                      'catalog_source': 'command-code@1.79.2',
                      'context_length': 262000,
                      'entitlement': 'subscription',
                      'id': 'tencent/hy3-paid',
                      'min_plan': 'go',
                      'name': 'Tencent Hy3',
                      'native_protocol': 'chat',
                      'reference_pricing': {'input': 0.14, 'output': 0.58, 'unit': 'USD/1M tokens'}},
 'tencent/hy4-preview': {'billing_mode': 'paid',
                         'catalog_source': 'command-code@1.79.2',
                         'context_length': 1050000,
                         'entitlement': 'subscription',
                         'id': 'tencent/hy4-preview',
                         'min_plan': 'go',
                         'name': 'Tencent Hy4 Preview',
                         'native_protocol': 'chat',
                         'reference_pricing': {'input': 0.834, 'output': 2.501, 'unit': 'USD/1M tokens'}},
 'thinkingmachines/inkling': {'billing_mode': 'paid',
                              'catalog_source': 'command-code@1.79.2',
                              'context_length': 256000,
                              'entitlement': 'subscription',
                              'id': 'thinkingmachines/inkling',
                              'min_plan': 'go',
                              'name': 'Inkling',
                              'native_protocol': 'chat',
                              'reference_pricing': {'input': 1.0, 'output': 4.05, 'unit': 'USD/1M tokens'}},
 'thinkingmachines/inkling-small': {'billing_mode': 'paid',
                                    'catalog_source': 'command-code@1.79.2',
                                    'context_length': 1000000,
                                    'entitlement': 'subscription',
                                    'id': 'thinkingmachines/inkling-small',
                                    'min_plan': 'go',
                                    'name': 'Inkling Small',
                                    'native_protocol': 'chat',
                                    'reference_pricing': {'input': 0.5,
                                                          'output': 1.2,
                                                          'unit': 'USD/1M tokens'}},
 'xai/grok-4.5': {'billing_mode': 'paid',
                  'catalog_source': 'command-code@1.79.2',
                  'context_length': 500000,
                  'entitlement': 'subscription',
                  'id': 'xai/grok-4.5',
                  'min_plan': 'go',
                  'name': 'Grok 4.5',
                  'native_protocol': 'chat',
                  'reference_pricing': {'input': 2.0, 'output': 6.0, 'unit': 'USD/1M tokens'}},
 'xai/grok-4.6': {'billing_mode': 'paid',
                  'catalog_source': 'command-code@1.79.2',
                  'context_length': 500000,
                  'entitlement': 'subscription',
                  'id': 'xai/grok-4.6',
                  'min_plan': 'goat',
                  'name': 'Grok 4.6',
                  'native_protocol': 'chat',
                  'reference_pricing': {'input': 2.0, 'output': 6.0, 'unit': 'USD/1M tokens'}},
 'xai/grok-4.7': {'billing_mode': 'paid',
                  'catalog_source': 'command-code@1.79.2',
                  'context_length': 500000,
                  'entitlement': 'subscription',
                  'id': 'xai/grok-4.7',
                  'min_plan': 'goat',
                  'name': 'Grok 4.7',
                  'native_protocol': 'chat',
                  'reference_pricing': {'input': 2.0, 'output': 6.0, 'unit': 'USD/1M tokens'}},
 'xiaomi/mimo-v2.5': {'billing_mode': 'paid',
                      'catalog_source': 'command-code@1.79.2',
                      'context_length': 1000000,
                      'entitlement': 'subscription',
                      'id': 'xiaomi/mimo-v2.5',
                      'min_plan': 'go',
                      'name': 'MiMo V2.5',
                      'native_protocol': 'chat',
                      'reference_pricing': {'input': 0.14, 'output': 0.28, 'unit': 'USD/1M tokens'}},
 'xiaomi/mimo-v2.5-pro': {'billing_mode': 'paid',
                          'catalog_source': 'command-code@1.79.2',
                          'context_length': 1000000,
                          'entitlement': 'subscription',
                          'id': 'xiaomi/mimo-v2.5-pro',
                          'min_plan': 'go',
                          'name': 'MiMo V2.5 Pro',
                          'native_protocol': 'chat',
                          'reference_pricing': {'input': 0.435, 'output': 0.87, 'unit': 'USD/1M tokens'}},
 'xiaomi/mimo-v2.6-flash': {'billing_mode': 'paid',
                            'catalog_source': 'command-code@1.79.2',
                            'context_length': 1050000,
                            'entitlement': 'subscription',
                            'id': 'xiaomi/mimo-v2.6-flash',
                            'min_plan': 'go',
                            'name': 'MiMo V2.6 Flash',
                            'native_protocol': 'chat',
                            'reference_pricing': {'input': 0.14, 'output': 0.28, 'unit': 'USD/1M tokens'}},
 'xiaomi/mimo-v2.6-pro': {'billing_mode': 'paid',
                          'catalog_source': 'command-code@1.79.2',
                          'context_length': 1050000,
                          'entitlement': 'subscription',
                          'id': 'xiaomi/mimo-v2.6-pro',
                          'min_plan': 'go',
                          'name': 'MiMo V2.6 Pro',
                          'native_protocol': 'chat',
                          'reference_pricing': {'input': 0.435, 'output': 0.87, 'unit': 'USD/1M tokens'}},
 'xiaomi/mimo-v2.6-pro-ultraspeed': {'billing_mode': 'paid',
                                     'catalog_source': 'command-code@1.79.2',
                                     'context_length': 1050000,
                                     'entitlement': 'subscription',
                                     'id': 'xiaomi/mimo-v2.6-pro-ultraspeed',
                                     'min_plan': 'goat',
                                     'name': 'MiMo V2.6 Pro UltraSpeed',
                                     'native_protocol': 'chat',
                                     'reference_pricing': {'input': 4.35,
                                                           'output': 8.7,
                                                           'unit': 'USD/1M tokens'}},
 'z-ai/glm-5.3-flash': {'billing_mode': 'paid',
                        'catalog_source': 'command-code@1.79.2',
                        'context_length': 1050000,
                        'entitlement': 'subscription',
                        'id': 'z-ai/glm-5.3-flash',
                        'min_plan': 'go',
                        'name': 'GLM-5.3 Flash',
                        'native_protocol': 'chat',
                        'reference_pricing': {'input': 0.15, 'output': 0.5, 'unit': 'USD/1M tokens'}},
 'z-ai/glm-5.3-flashx': {'billing_mode': 'paid',
                         'catalog_source': 'command-code@1.79.2',
                         'context_length': 1000000,
                         'entitlement': 'subscription',
                         'id': 'z-ai/glm-5.3-flashx',
                         'min_plan': 'go',
                         'name': 'GLM-5.3 FlashX',
                         'native_protocol': 'chat',
                         'reference_pricing': {'input': 0.37, 'output': 1.25, 'unit': 'USD/1M tokens'}},
 'zai-org/GLM-5': {'billing_mode': 'paid',
                   'catalog_source': 'command-code@1.79.2',
                   'context_length': 200000,
                   'entitlement': 'subscription',
                   'id': 'zai-org/GLM-5',
                   'min_plan': 'go',
                   'name': 'GLM-5',
                   'native_protocol': 'chat',
                   'reference_pricing': {'input': 1.0, 'output': 3.2, 'unit': 'USD/1M tokens'}},
 'zai-org/GLM-5.1': {'billing_mode': 'paid',
                     'catalog_source': 'command-code@1.79.2',
                     'entitlement': 'subscription',
                     'id': 'zai-org/GLM-5.1',
                     'min_plan': 'go',
                     'name': 'GLM-5.1',
                     'native_protocol': 'chat',
                     'reference_pricing': {'input': 1.4, 'output': 4.4, 'unit': 'USD/1M tokens'}},
 'zai-org/GLM-5.2': {'billing_mode': 'paid',
                     'catalog_source': 'command-code@1.79.2',
                     'context_length': 1000000,
                     'entitlement': 'subscription',
                     'id': 'zai-org/GLM-5.2',
                     'min_plan': 'go',
                     'name': 'GLM-5.2',
                     'native_protocol': 'chat',
                     'reference_pricing': {'input': 1.4, 'output': 4.4, 'unit': 'USD/1M tokens'}},
 'zai-org/GLM-5.2-Fast': {'billing_mode': 'paid',
                          'catalog_source': 'command-code@1.79.2',
                          'context_length': 1000000,
                          'entitlement': 'subscription',
                          'id': 'zai-org/GLM-5.2-Fast',
                          'min_plan': 'go',
                          'name': 'GLM-5.2 Fast',
                          'native_protocol': 'chat',
                          'reference_pricing': {'input': 3.0, 'output': 10.25, 'unit': 'USD/1M tokens'}},
 'zai-org/GLM-5.3': {'billing_mode': 'paid',
                     'catalog_source': 'command-code@1.79.2',
                     'context_length': 1000000,
                     'entitlement': 'subscription',
                     'id': 'zai-org/GLM-5.3',
                     'min_plan': 'go',
                     'name': 'GLM-5.3',
                     'native_protocol': 'chat',
                     'reference_pricing': {'input': 1.4, 'output': 4.4, 'unit': 'USD/1M tokens'}}}
